FROM elasticsearch:7.16.3

COPY plugins/analysis-smartcn-7 /usr/share/elasticsearch/plugins/analysis-smartcn
COPY plugins/elasticsearch-analysis-stconvert-7 /usr/share/elasticsearch/plugins/analysis-stconvert
